### ISSUE TITLE
Can't start with npm start or build

### ISSUE THREAD

**Issue by santiagoworkana** [carlelieser/Flixerr#21]
I'm trying to start the solution but it give me the following error:
![image](https://user-images.githubusercontent.com/33036105/77332093-58796600-6d00-11ea-9b9c-4daed554bffb.png)

And if i run npm run build i get the following

`npm run build

> flixerr@1.5.4 build C:\Users\snisn\Documents\Projects\Flixer\Flixerr
> electron-builder --dir

  • electron-builder  version=21.2.0 os=10.0.18362
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=bufferutil@4.0.1, utf-8-validate@5.0.2, grpc@1.24.2 platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=5.0.13 appOutDir=build\win-unpacked
  ⨯ Cannot find module 'C:\Users\snisn\Documents\Projects\Flixer\Flixerr\notarize.js'
Require stack:
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\platformPackager.js
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\winPackager.js
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\packager.js
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\index.js
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\electron-builder\out\builder.js
- C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\electron-builder\out\cli\cli.js  stackTrace=

                                                                                           Error: Cannot find module 'C:\Users\snisn\Documents\Projects\Flixer\Flixerr\notarize.js'

                                                                                           Require stack:

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\platformPackager.js     

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\winPackager.js

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\packager.js

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\out\index.js

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\electron-builder\out\builder.js

                                                                                           - C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\electron-builder\out\cli\cli.js

                                                                                               at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)

                                                                                               at Function.Module._load (internal/modules/cjs/loader.js:859:27)

                                                                                               at Module.require (internal/modules/cjs/loader.js:1036:19)

                                                                                               at require (internal/modules/cjs/helpers.js:72:18)

                                                                                               at resolveFunction (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\platformPackager.ts:653:13)

                                                                                               at WinPackager.doPack (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\platformPackager.ts:245:23)

                                                                                               at WinPackager.pack (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\platformPackager.ts:114:5)

                                                                                               at Packager.doBuild (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\packager.ts:437:9)

                                                                                               at executeFinally (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\builder-util\src\promise.ts:12:14)

                                                                                               at Packager._build (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\packager.ts:366:31)

                                                                                               at Packager.build (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\app-builder-lib\src\packager.ts:330:12)

                                                                                               at executeFinally (C:\Users\snisn\Documents\Projects\Flixer\Flixerr\node_modules\builder-util\src\promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flixerr@1.5.4 build: `electron-builder --dir`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flixerr@1.5.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

Do oyu knoiw what I'm missing?

**Comment by carlelieser** [comment]
Have you tried running `npm run compile` before running `npm start`? If you're just trying to get it running to develop, set the global develop variable in the main.js file to true.

**Comment by carlelieser** [comment]
This was due to some changes with the webRequest onHeaderReceived event. This was fixed in 1.5.6 :)

**Comment by santiagoworkana** [comment]
Yes i tried, but I till get the error about filters must have a valid url :S

**Comment by carlelieser** [comment]
@santiagoworkana Can you try doing a pull. I believe I fixed the issue. Let me know.

**Comment by santiagoworkana** [comment]
Just did it and worked! :) thanks!! now time to play wit it!

**Comment by carlelieser** [comment]
@santiagoworkana Great, glad it worked!
